apiVersion: v1
kind: Namespace
metadata:
  name: wedding-invitation
  labels:
    name: wedding-invitation
    environment: production
  annotations:
    description: "Wedding Invitation Application Namespace"